name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees:
  - X1nto
body:
  - type: textarea
    id: device-info
    attributes:
      label: Device
      description: What device are you using?
      value: |
        Device:
        Operating System:
        Android Version:
    validations:
      required: true
  - type: textarea
    id: manager-version
    attributes:
      label: Version
      description: What version of Vanced Manager are you using?
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Describe the bug and how to reproduce it in as much detail as possible.
    validations:
      required: true
  - type: checkboxes
    id: is-manager-bug
    attributes:
      label: Additional checks
      options:
      - label: I have checked other bug reports and this is not a duplicate.
        required: true
      - label: This is a bug in Vanced Manager and NOT YouTube Vanced/YouTube Vanced Music/Vanced microG.
        required: true
