name: Debug APK Builder

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant rights
        run: chmod +x ./gradlew

      - name: Build debug APK with Gradle
        run: ./gradlew assembleDebug

      - name: Upload Debug
        uses: actions/upload-artifact@v2
        with:
          name: 'Manager'
          path: app/build/outputs/apk/debug/app-debug.apk
